name: oracle
description: A new Flutter project.


publish_to:



version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.10.0
  firebase_core_platform_interface: ^4.2.3
  firebase_messaging_platform_interface: ^3.1.5
  firebase_messaging_web: ^2.2.6
  meta: ^1.3.0
  firebase_messaging: ^11.2.5
  http: ^0.13.4
  flutter_local_notifications: ^9.2.0
  conditioned: ^0.1.0-dev.1
  flutter_conditional_rendering: ^2.0.0
  hand_signature: ^2.1.1

  liquid_swipe: ^2.1.1



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true






  fonts:
    - family: Corinthia
      fonts:
        - asset: fonts/Corinthia-Regular.ttf

#    - family: AbrilFatface
#      fonts:
#        - asset: fonts/AbrilFatface-Regular.ttf
